# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZeSMoYrO3/WQvjCvScz3j6JKupSHD3Gl/x28TxWeDYyTfykJU5TYbobI7d3jxADrzc9xhWXm7Ja+fhEoPa7xd2HsvUXPT+AEjSzvTQ5MemLBLERT/J4Nl29wfGMx4/XbtPJ2PP7ynkEOTW1iCX/UHsYocsU0wq8GBPJXEj69X2h2tEctty5FOSXKU3htPhPfeQOQPO/WhiisHSobIIv/KljIBB860ixUXfJYDbsQXVP2Nqq7YfSQ6twpR3tIasRqj1aGiV4AOoW3BaDLS6Eiivbp8zObsJtyjyPHGQJBFgKp3Fvt3Bmotapge31BG9QciaE0X6qCoFNEWJkJCBOXk+300x2pIw9fq3LcbrHexHxfqUzlrdn5Kc0F9UfYF4O1CUIbd15SDvZBNphdCB/lmTTdMvco4+KthWdWz2X1QX86xx94LeHGh3/40tonG5ygABOxviLLBoagQ+4GfkxKnZ4HbCZpIcXgxK/jeHwEhfnPdINnTIOp4l5YKVy6O1/DBxyN1nJ3L+gdg0q5N1IZrrzP7Ttp1EmvEM+YMimReUnOrQ27OtSi3V+eXrKIggSfTAEioUocmZn+2jEwAQ+H9gAge4tne5g2KzQ8pUdF6AglCYn84xEG1WsJEvigFrZcWDU4WBLc49/S6/ir3McPlqjMINBDax3SnbKVQ9HAEg0="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
