# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "F0/zX9Yv5cl0Kz1P7tQDazZpI1TppPq5xBSgz21EY8nCaubBSErdjgU3XRuwfaYO18AMBbz28oAD1YL6fCE8BM5PwD3/6nC+OmOytxCGyJ4RtecvAPNo994YX9dwCh8qaXr2i/lHPl3haotS88RVCQcA8FpyDyfxCsZPW0y6XDQK3wk3jfOPhQ1Q9U6qJRiirO2bSFIZ1ooycCj/Aa8jYEepCqFHRaEmXd51yo1J4LEFxwA8g335UiP8nffiV/Sn+2sMPB8T4r+bCou1Ku0m1KeCDaExKRG49WOpFzKOCk3QYg35JrHn7Sc2sbGTV9mQ/iYu+4aE0bL6c5Ryev4toDfio1wQ1PsWeyR8ZhHrn2Ukg5sd7sExlVroniXFANxfxxE2Ud9lDLuRS7ySPRvxMYZ00WHRQkpPH/+i3N3NNv4jaBkhQ6go5W804K0LuqvAYozjodL4wqO0TxDhgWgNTWBTIiLR346hWwivzmqR0KSEBMvn+Q7PKq89TYEpmML453sUMsgI6FjjUKBuRjZ+euWrABAiSLa8ii+BKQvyPOK3ZDR6kcdsIitEGQK4Tmwm61+qLNi+Yv0IUxrYhRkHVnvtMcBsKi5nCn1tbzf7rQOBbvS93SunqUtjE17CLaYwM+6ysTKz+bsS2Qd/ZmBfEK9aoB6URvkZ2d9XB5jqtVk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
