travis:
  secure:
    BINSTAR_TOKEN: ZeSMoYrO3/WQvjCvScz3j6JKupSHD3Gl/x28TxWeDYyTfykJU5TYbobI7d3jxADrzc9xhWXm7Ja+fhEoPa7xd2HsvUXPT+AEjSzvTQ5MemLBLERT/J4Nl29wfGMx4/XbtPJ2PP7ynkEOTW1iCX/UHsYocsU0wq8GBPJXEj69X2h2tEctty5FOSXKU3htPhPfeQOQPO/WhiisHSobIIv/KljIBB860ixUXfJYDbsQXVP2Nqq7YfSQ6twpR3tIasRqj1aGiV4AOoW3BaDLS6Eiivbp8zObsJtyjyPHGQJBFgKp3Fvt3Bmotapge31BG9QciaE0X6qCoFNEWJkJCBOXk+300x2pIw9fq3LcbrHexHxfqUzlrdn5Kc0F9UfYF4O1CUIbd15SDvZBNphdCB/lmTTdMvco4+KthWdWz2X1QX86xx94LeHGh3/40tonG5ygABOxviLLBoagQ+4GfkxKnZ4HbCZpIcXgxK/jeHwEhfnPdINnTIOp4l5YKVy6O1/DBxyN1nJ3L+gdg0q5N1IZrrzP7Ttp1EmvEM+YMimReUnOrQ27OtSi3V+eXrKIggSfTAEioUocmZn+2jEwAQ+H9gAge4tne5g2KzQ8pUdF6AglCYn84xEG1WsJEvigFrZcWDU4WBLc49/S6/ir3McPlqjMINBDax3SnbKVQ9HAEg0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
